# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0360d7b214f792f7fd119797467d6d22e188c56f4647012866078d5130b9e3763655f11b296e6b667d8478920e4e60b56d8bfba6704587de396752ab2fa65f6e

test:
  secret_key_base: ef58ec4d3234f1c10368541549ea06ca9d9927090c88bf42e91b62f6bfbd39710eb68d3b2a03a43631766a1cd2f4a3f29ab3cf52df7004529315f98a1e42c772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
