# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b973eb4480b1885d24769f0c033b30fcd1b7d17d28f1629c067310b26001e676bd58fbda7734b92dff33bb36a09a7aa381fe7937fedcbe504bc5482896dd7508

test:
  secret_key_base: a8f92c3b7ce7a21ddb9c0fdede9c96f3f5bb843a3a26132ecac27540d93470837dea1bc65d248c16f1930a81d1394955c0746e4f9776a7adbdc5a94a4652e437

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
