# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f5d70021b316e5a86744a1564d7e1bc23f9c48521debfdd470e804d6086553f8a9cf73d30baffea1c963b73600675ff79851ed0af4c6ee924e93164904fe5d

test:
  secret_key_base: b7031a2768bfa8085cc2ab81d0d8f190f980b3b617de23ff3a7005c4317322e8d9c592eaec6106c0c0319ee94940931f960fc6e2776ccb2f932f84350a8dde3e

production:
  secret_key_base: e921f0539973afd339e249189627256c0409022107c46d95e391ba379eab5c80b4253bfad88cfcfcb1879ec905f41b8c474d159553e5dd1f2959a342fb716b72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
